---
# Source: nfs-subdir-external-provisioner/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner-3.0.0
    heritage: Helm
    release: nfs-subdir-external-provisioner
  name: leader-locking-nfs-subdir-external-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
