---
# Source: nfs-subdir-external-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner-3.0.0
    heritage: Helm
    release: nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner
  namespace: nfs
