---
# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-kube-prometheus-alertmanager
  namespace: default
  labels:
    app: kube-prometheus-stack-alertmanager
    
    chart: kube-prometheus-stack-10.3.3
    release: "prometheus"
    heritage: "Helm"
spec:
  baseImage: quay.io/prometheus/alertmanager
  version: v0.21.0
  replicas: 1
  listenLocal: false
  serviceAccountName: prometheus-kube-prometheus-alertmanager
  externalUrl: http://prometheus-kube-prometheus-alertmanager.default:9093
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  portName: web
