---
# Source: kube-prometheus-stack/templates/alertmanager/psp-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-kube-prometheus-alertmanager
  namespace: default
  labels:
    app: kube-prometheus-stack-alertmanager
    
    chart: kube-prometheus-stack-10.3.3
    release: "prometheus"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-kube-prometheus-alertmanager
subjects:
  - kind: ServiceAccount
    name: prometheus-kube-prometheus-alertmanager
    namespace: default
