---
# Source: kube-prometheus-stack/templates/exporters/kube-state-metrics/serviceMonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-kube-prometheus-kube-state-metrics
  namespace: default
  labels:
    app: kube-prometheus-stack-kube-state-metrics
    
    chart: kube-prometheus-stack-10.3.3
    release: "prometheus"
    heritage: "Helm"
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/instance: "prometheus"
