---
# Source: kube-prometheus-stack/templates/prometheus-operator/psp-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-kube-prometheus-operator-psp
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-10.3.3
    release: "prometheus"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-kube-prometheus-operator-psp
subjects:
  - kind: ServiceAccount
    name: prometheus-kube-prometheus-operator
    namespace: default
