---
# Source: kube-prometheus-stack/templates/prometheus/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-kube-prometheus-prometheus
  namespace: default
  labels:
    app: kube-prometheus-stack-prometheus
    
    chart: kube-prometheus-stack-10.3.3
    release: "prometheus"
    heritage: "Helm"
imagePullSecrets:
  []
