---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: elk
  labels:
    k8s-app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        # image: docker.elastic.co/kibana/kibana-oss:6.8.4
        image: jmb12686/kibana:v7.7.1
        # env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
        env:
        - name: CLUSTER_NAME
          value: elasticsearch-logging      
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP