---
# Source: kube-prometheus-stack/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-prometheus-node-exporter
  namespace: default
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-1.11.2
    release: "prometheus"
    heritage: "Helm"
imagePullSecrets:
  []
